FROM node:alpine AS builder

WORKDIR /build

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend ./

RUN npm run build

FROM node:alpine

WORKDIR /app

COPY --from=builder ./build/package*.json ./
COPY --from=builder ./build/dist ./dist
COPY --from=builder ./build/node_modules ./node_modules

RUN mkdir -p /app/uploads && chown -R node:node /app/uploads && chmod -R 777 /app/uploads
RUN mkdir -p /app/logs && chown -R node:node /app/logs

USER node

EXPOSE 8000

# Use nodemon for hot reload in development
CMD ["npm", "run", "start"]
